"""
Store all stickers that a bot can send to user.
"""

fish = ['BQADAgADBAADijc4AAFx0NNqDnJm4QI', 'BQADAgADBgADijc4AAH50MoMENn2lQI', 'BQADAgADCAADijc4AAGB93daGX3cWgI',
        'BQADAgADLQADijc4AAGBowxjAqAlGwI',
        'BQADAgADDgADijc4AAGOGq6J30OGfwI', 'BQADAgADEAADijc4AAESVXqKiwYE2wI', 'BQADAgADEgADijc4AAF00GirhpifXQI',
        'BQADAgADFAADijc4AAGtl5dISqHmiAI',
        'BQADAgADFgADijc4AAErJ-ihzzsO7wI', 'BQADAgADJwADijc4AAE3oUMhargOuAI', 'BQADAgADGQADijc4AAHtT7j-b6m-2QI',
        'BQADAgADGwADijc4AAEdwByBSe9kgQI',
        'BQADAgADHQADijc4AAEw0RBgpCTPAAEC', 'BQADAgADHwADijc4AAFXWsuIC4i6fAI', 'BQADAgADMwADijc4AAGU2NZK2N9ilwI']

gnidogadoids = ['BQADAgADDQADk81XAAF2ISvz1e1cZwI', 'BQADAgADDwADk81XAAF_FX9vSI0ZUgI', 'BQADAgADEQADk81XAAF57og3ZPGXNQI',
                'BQADAgADEwADk81XAAGPLvDl-q-8GQI',
                'BQADAgADjAADk81XAAH2oYm_MyQlKQI', 'BQADAgADigADk81XAAGP8kPSVTjNHQI', 'BQADAgADiAADk81XAAFhrgRCtLZ0JQI',
                'BQADAgADhgADk81XAAG_vC1oQ2LblAI',
                'BQADAgADhAADk81XAAHSNzBXP3fM3gI', 'BQADAgADggADk81XAAFv08mRRBMhtwI', 'BQADAgADgAADk81XAAEwHUrkqz_d6wI',
                'BQADAgADfgADk81XAAEyUjRJEr48QAI',
                'BQADAgADfAADk81XAAEHvxMGv8_1YQI', 'BQADAgADegADk81XAAEKJF8elYIyWwI', 'BQADAgADeAADk81XAAH5MZSu2t3MNwI',
                'BQADAgADdgADk81XAAH-AyIuAAHuLtcC']
